Add Penguin Hook to List
PenguinMod/PenguinMod-ExtensionsGallery pull request #110
Opened 2024-01-08 13:09 UTC by cicerorph

2024-01-08 16:42 UTC, cicerorph commented
please approve

2024-02-17 05:23 UTC, SharkPool-SP commented
Ill merge it whenever you add a thumbnail. Ik yall have one im just too lazy to find it rn 
![image](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/139097378/0da4c6cf-a02f-4f88-ae11-ca1f9374a72c)

2024-02-17 10:16 UTC, cicerorph commented
Ready once again

2024-02-21 04:19 UTC, SharkPool-SP commented
Use Scratch.Cast.toString() for all arguments that is sent

2024-02-23 19:54 UTC, cicerorph commented
btw no offense with that commit k?

2024-02-23 20:01 UTC, SharkPool-SP commented
> btw no offense with that commit k?
> 
> 

You keep the JSON.stringify() that's different

2024-02-23 20:46 UTC, RedMan13 commented
> Use Scratch.Cast.toString() for all arguments that is sent

do not do this unless you have disabled type casting for the input
penguinmod casts the types of inputs for you aslong as you dont either tell it not too or set the type of the input

2024-02-23 20:49 UTC, RedMan13 commented
ok i missed something but this is also still wrong because you have to use json.stringify to handle json objects as cast.tostring will not run json.stringify for you if you do pass an object

2024-02-23 20:51 UTC, SharkPool-SP commented
> ok i missed something but this is also still wrong because you have to use json.stringify to handle json objects as cast.tostring will not run json.stringify for you if you do pass an object

I know. Idk why he did it for all json stuff. I just said the arguments

2024-02-23 20:51 UTC, RedMan13 commented
... but like i said, thats absurdly pointless and just wastes time cause penguinmod does that for you

2024-03-06 22:57 UTC, JeremyGamer13 requested changes

2024-03-06 22:57 UTC, JeremyGamer13 commented on static/extensions/MubiLop/penguinhook.js
> +                id: 'penguinhook',
add your name or part of your name in the extension ID

2024-03-06 22:57 UTC, JeremyGamer13 commented on static/extensions/MubiLop/penguinhook.js
> +                color2: "#02b4e0",
If all colors are the same then you shouldnt be defining past color1 or itll just look bad

2024-03-06 22:57 UTC, JeremyGamer13 commented on static/extensions/MubiLop/penguinhook.js
> +            return fetch(webhookUrl, {
Scratch.canFetch() is not checked before this, meaning this will just send data to a webhook without the user knowing at all

2024-03-06 22:57 UTC, JeremyGamer13 commented on static/extensions/MubiLop/penguinhook.js
> +            return fetch(webhookUrl, {
Scratch.canFetch() is not checked before this, meaning this will just send data to a webhook without the user knowing at all

2024-03-06 22:57 UTC, JeremyGamer13 commented on static/extensions/MubiLop/penguinhook.js
> +                return fetch(args.WEBHOOK, {
Scratch.canFetch() is not checked before this, meaning this will just send data to a random url without the user knowing at all

2024-03-06 22:57 UTC, JeremyGamer13 commented on static/extensions/MubiLop/penguinhook.js
> +// By MubiLop from Ruby Team (https://rubyteam.tech/)
rubyteam.tech lists this extension under the [Attribution-NonCommercial-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1) license, which does not comply with MIT

2024-03-06 23:49 UTC, JeremyGamer13 commented
Scratch.canFetch returns a promise

2024-03-10 07:15 UTC, JeremyGamer13 commented
Scratch.canFetch returns a promise, so all of these checks for Scratch.canFetch just dont work properly

2024-03-18 01:03 UTC, JeremyGamer13 approved these changes

2024-03-18 01:05 UTC, merged