Number Utilities
PenguinMod/PenguinMod-ExtensionsGallery pull request #246
Opened 2024-10-29 13:44 UTC by cicerorph

2024-10-29 13:53 UTC, hammouda101010 commented
this should be renamed to "number formating" tbh i'm getting sick of these "utilites" names

2024-10-29 14:28 UTC, cicerorph commented
> this should be renamed to "number formating" tbh i'm getting sick of these "utilites" names

Idc

2024-10-29 14:28 UTC, cicerorph commented
It has some other utilities other than formatting

2024-10-29 14:47 UTC, cicerorph commented
Fixed it lol

2024-10-29 15:23 UTC, JeremyGamer13 commented
if your gonna have error messages, i would recommend just throwing errors so users can use the native try catch blocks instead of checking if the returned value starts with error

2024-10-29 15:24 UTC, CodeFoxy-Github commented
11:24 wtf

JeremyGamer13 ***@***.***>於 2024年10月29日 週二，下午11:23寫道：

> if your gonna have error messages, i would recommend just throwing errors
> so users can use the native try catch blocks instead of checking if the
> returned value starts with error
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/pull/246#issuecomment-2444591444>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXAM7QVBZOVDZ7LZAEKXRQTZ56SAHAVCNFSM6AAAAABQZ4QFF6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBUGU4TCNBUGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> com>
>

2024-10-29 16:11 UTC, cicerorph commented
> if your gonna have error messages, i would recommend just throwing errors so users can use the native try catch blocks instead of checking if the returned value starts with error

Updated.

2024-10-29 18:26 UTC, jwklong requested changes
a feww changes that would make this better

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +              LOCALE: {
accept reporters?

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +              CURRENCY: {
accept reporters?

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +            opcode: 'parseNumber',
numbers already get parsed by scratch automatically, giving this block no purpose

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid number or locale');
if the locale is invalid just make it use system locale

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid input');
args.decimals needs to be converted to number, making invalid input pointless

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return Number(args.NUMBER).toPrecision(args.PRECISION);
args.precision needs to be converted to number, making invalid input pointless

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return Number(args.NUMBER).toExponential(args.DECIMALS);
args.decimals needs to be converted to number, making invalid input pointless

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid input');
just make it use like,,, system currency or whatever

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid input');
args.decimals needs to be converted to number, making invalid input pointless

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid input');
args.number needs to be converted to number, making invalid input pointless

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return Number.isNaN(parsed) ? 'Error: Invalid number' : parsed;
if its NaN just return NaN no big deal you have a block to check if it is just let people use that if they dont want NaN

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid input');
not possible i believe

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        throw new Error('Error: Invalid input');
not possible

2024-10-29 18:26 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        const max = Number(args.MAX);
if min > max swap the two around

2024-10-29 19:02 UTC, RedMan13 commented
also just as a global note: your supposed to use Scratch.Cast.ToNumber() not Number()
also none of the inputs tell pm to not type cast them so all of the inputs are getting casted twice for no reason

2024-10-29 23:46 UTC, cicerorph commented
Just made cast work

2024-10-30 01:20 UTC, RedMan13 commented
thats only part of what i meant.........
the casts are a waste of time all together because pm itself is performing the typecasts automatically for you.............

2024-10-30 12:18 UTC, hammouda101010 commented
> thats only part of what i meant......... the casts are a waste of time all together because pm itself is performing the typecasts automatically for you.............

that's not a problem. **Turbowarp** doesn't do this by default so you'll have to do this by yourself in your extensions to make it compatible or atleast make it work.

2024-10-30 13:56 UTC, RedMan13 commented
> > thats only part of what i meant......... the casts are a waste of time all together because pm itself is performing the typecasts automatically for you.............
> 
> that's not a problem. **Turbowarp** doesn't do this by default so you'll have to do this by yourself in your extensions to make it compatible or atleast make it work.

aut this is the **PenguinMod** extension gallery

2024-10-30 13:58 UTC, hammouda101010 commented
> > > thats only part of what i meant......... the casts are a waste of time all together because pm itself is performing the typecasts automatically for you.............
> > 
> > 
> > that's not a problem. **Turbowarp** doesn't do this by default so you'll have to do this by yourself in your extensions to make it compatible or atleast make it work.
> 
> aut this is the **PenguinMod** extension gallery

however you got a point. this is **NOT** the **Turbowarp** extension gallery. I was just talking abt compability.

2024-10-30 16:22 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return Cast.toNumber(args.NUMBER).toLocaleString(this.systemLocale); // jwklong asked for this
just change locale to this and get rid of the error:
```js
const locale = Object.values(LANGUAGE_CODES).find(v => v == args.LOCALE && v != 'system') || this.systemLocale
```
problem solved

2024-10-30 16:23 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return 'Error: Invalid input';
you've downgraded from throwing to returning 😭 also you DONT need a error here

2024-10-30 16:23 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return 'Error: Invalid input';
same as above

2024-10-30 16:30 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        });
if it errors just format it without currency 🤯

2024-10-30 16:30 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return 'Error: Invalid input';
error not possible

2024-10-30 16:30 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return 'Error: Invalid input';
same as above

2024-10-30 16:31 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> -    }
why did you get rid of this block?

2024-10-30 16:31 UTC, jwklong commented on static/extensions/MubiLop/numutils.js
> +        return 'Error: Invalid input';
error not possible

2024-10-30 17:34 UTC, cicerorph commented on static/extensions/MubiLop/numutils.js
> -    }
Bcs it's no use anyway

2024-10-30 17:54 UTC, ddededodediamante commented on static/extensions/MubiLop/numutils.js
> -    }
You can use it to see if a variable is a number or not 
so useful

2024-10-30 18:16 UTC, jwklong approved these changes
yeahh its good i guess

2024-10-30 18:16 UTC, jwklong commented on src/lib/Documentation/NumberUtilities.md
>  ## Error Handling
jus a suggestion but this doesn't really seemmmm useful anymore

2024-10-30 18:17 UTC, merged

2024-10-30 18:18 UTC, jwklong commented
> > thats only part of what i meant......... the casts are a waste of time all together because pm itself is performing the typecasts automatically for you.............
> 
> that's not a problem. **Turbowarp** doesn't do this by default so you'll have to do this by yourself in your extensions to make it compatible or atleast make it work.

boo hoo