Create Orientation_Detection.js (from JosiahW2011)
PenguinMod/PenguinMod-ExtensionsGallery pull request #264
Opened 2024-12-27 05:09 UTC by JosiahW2011

Thumbnail:
![O](https://github.com/user-attachments/assets/b121710c-b003-4610-8207-81dd28503548)

2024-12-27 18:15 UTC, JosiahW2011 reviewed
👍

2025-01-31 17:08 UTC, JeremyGamer13 requested changes

2025-01-31 17:08 UTC, JeremyGamer13 commented on static/extensions/JosiahW2011/Orientation_Detection.js
> +                id: "OrDe",
add your name to the ID somewhere, this is too little for the ID

2025-01-31 17:08 UTC, JeremyGamer13 commented on static/extensions/JosiahW2011/Orientation_Detection.js
> +                        text: 'isLandscape?',
preferably rename this to "is landscape?"

2025-01-31 17:08 UTC, JeremyGamer13 commented on static/extensions/JosiahW2011/Orientation_Detection.js
> +                        text: 'isPortrait?',
preferably rename this to "is portrait?"

2025-01-31 17:08 UTC, JeremyGamer13 commented on static/extensions/JosiahW2011/Orientation_Detection.js
> +                        text: 'currentOrientation?',
preferably rename this to "current orientation"

2025-03-12 18:29 UTC, SharkPool-SP commented
this has gone stale

2025-03-12 18:29 UTC, closed without merging

2025-09-30 22:46 UTC, JosiahW2011 commented
I have quit using Penguinmod for quite some time, so I could barely care about it anymore.

2025-09-30 22:58 UTC, LordCat0 commented
uhhhh ok?