Create ListsPlus.js
PenguinMod/PenguinMod-ExtensionsGallery pull request #3
Opened 2023-07-26 04:41 UTC by pooiod

Lists+ takes your Scratch projects to a whole new level by introducing nested lists, allowing you to organize information in a more complex and dynamic way. Similar to how you might have folders within folders on your computer, nested lists act like boxes inside boxes, providing a powerful way to manage data efficiently.

![image](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/82846639/84db7d91-d66a-4826-9187-0c599a94f36e)

2023-07-28 22:07 UTC, JeremyGamer13 commented
putting an invalid list seems to just make the block run forever, maybe you could make it just pretend like an empty list was used if the list is invalid?

also ideally the extension ID should have your name somewhere in it

2023-10-10 08:43 UTC, SharkPool-SP commented
array blocks
![IMG_6214](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/139097378/b4f04f31-16d3-479d-9ae2-7fd66a1c0d01)

2024-01-03 06:24 UTC, RedMan13 commented
@pooiod :trollface:

2024-02-09 23:57 UTC, JeremyGamer13 requested changes
this PR still hasnt been updated, so i'd like to leave it with a change request to mark that there is a reason this isnt merged yet

-putting an invalid list seems to just make the blocks break, maybe you could make it just pretend like an empty list was used if the list is invalid?
- ideally the extension ID should have your name somewhere in it
- the thumbnail may be misleading for some people

2025-02-09 05:36 UTC, SharkPool-SP commented
this has gone stale

2025-02-09 05:36 UTC, closed without merging